### ISSUE TITLE
Exception Unable to determine if root directory exists when compiling a project

### ISSUE THREAD

**Issue by OndrejSpanel** [scala-js/jsdependencies#45]
A have a large project which I am now trying to update from Scala.js 0.6.32 to 1.1.1.  After updating sbt files as needed I get following error:

```text
[error] (tempiJS / Compile / jsDependencyManifests) java.nio.file.FileSystemException: D:\Users\xxxx\AppData\Local\Coursier\cache\v1\https\maven.pkg.github.com\OpenGrabeso\packages\com\github\opengrabeso\threejs-facade_sjs1_2.12\0.0.114-0.0.4\threejs-facade_sjs1_2.12-0.0.114-0.0.4.jar: Unable to determine if root directory exists
[error] (tempiJS / Compile / scalaJSNativeLibraries) java.nio.file.FileSystemException: D:\Users\xxx\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-compiler\2.12.12\scala-compiler-2.12.12.jar: Unable to determine if root directory exists
```

I have verified both files mentioned in those errors exist and appear to be fine.

My versions are:

```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.1.1")

addSbtPlugin("org.scala-js" % "sbt-jsdependencies" % "1.0.1")

addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.1.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.7.4")
```

```
sbt.version = 1.3.13
```

Full stack obtained by using `last`:

```text
[error] java.nio.file.FileSystemException: D:\Users\xxx\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-compiler\2.12.12\scala-compiler-2.12.12.jar: Unable to determine if root directory exists
[error]         at java.nio.file.Files.createDirectories(Files.java:756)
[error]         at org.scalajs.jsdependencies.sbtplugin.JSDependenciesPlugin$.makeVF$1(JSDependenciesPlugin.scala:158)
[error]         at org.scalajs.jsdependencies.sbtplugin.JSDependenciesPlugin$.$anonfun$jarListEntries$4(JSDependenciesPlugin.scala:169)
[error]         at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
[error]         at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
[error]         at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
[error]         at scala.collection.AbstractIterator.to(Iterator.scala:1429)
[error]         at scala.collection.TraversableOnce.toList(TraversableOnce.scala:299)
[error]         at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:299)
[error]         at scala.collection.AbstractIterator.toList(Iterator.scala:1429)
[error]         at org.scalajs.jsdependencies.sbtplugin.JSDependenciesPlugin$.jarListEntries(JSDependenciesPlugin.scala:169)
[error]         at org.scalajs.jsdependencies.sbtplugin.JSDependenciesPlugin$.jsFilesInJar(JSDependenciesPlugin.scala:177)
[error]         at org.scalajs.jsdependencies.sbtplugin.JSDependenciesPlugin$.$anonfun$configSettings$20(JSDependenciesPlugin.scala:351)
[error]         at org.scalajs.jsdependencies.sbtplugin.JSDependenciesPlugin$.$anonfun$collectFromClasspath$2(JSDependenciesPlugin.scala:106)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
[error]         at org.scalajs.jsdependencies.sbtplugin.JSDependenciesPlugin$.collectFromClasspath(JSDependenciesPlugin.scala:103)
[error]         at org.scalajs.jsdependencies.sbtplugin.JSDependenciesPlugin$.$anonfun$configSettings$19(JSDependenciesPlugin.scala:352)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (tempiJS / Compile / scalaJSNativeLibraries) java.nio.file.FileSystemException: D:\Users\xxx\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-compiler\2.12.12\scala-compiler-2.12.12.jar: Unable to determine if root directory exists
```

**Comment by sjrd** [comment]
Thanks for the report. Would you be able to provide a minimal reproduction?

**Comment by OndrejSpanel** [comment]
I am not sure. The project where I see the problem is quite large. I will try if the issue will survive removing significant parts of it. Does the top of the stack (`makeVF` / `createDirectories`) make any sense?

**Comment by OndrejSpanel** [comment]
It went better than I expected. All you need for repro is a few sbt lines referencing one particular package. The project is available at https://github.com/OndrejSpanel/JSDepsRepro

Notes:
- you need to add `[github]` / `token` into  `.gitconfig` file in your home directory, so that you can access the package located at the GitHub Packages. The package is public, therefore any valid token should do
- I guess there might be something unusual with this particular package, but I am not sure what and the message I get from the build is certainly not helpful. The same package built for Scala 0.6.x works fine
- the project used to build the package is at https://github.com/OpenGrabeso/threejs-facade if necessary. The project is self-contained, publishing is done using GitHub workflows

**Comment by sjrd** [comment]
I think something is missing from your repro, as I can't get it to do anything:
```
...\JSDepsRepro>sbt
[info] welcome to sbt 1.3.13 (AdoptOpenJDK Java 1.8.0_222)
[info] loading global plugins from C:\Users\sjrdo\.sbt\1.0\plugins
[info] loading settings for project jsdepsrepro-build from metals.sbt,plugins.sbt ...
[info] loading project definition from C:\Users\sjrdo\Documents\Projets\JSDepsRepro\project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] loading settings for project jsdepsrepro from build.sbt ...
[info] set current project to JSDepsRepro (in build file:/C:/Users/sjrdo/Documents/Projets/JSDepsRepro/)
[info] sbt server started at local:sbt-server-3eb80fb517e77d1c6923
sbt:JSDepsRepro> clean
[warn] undefined keys `githubOwner` and `githubRepository`
[warn] retaining pre-existing publication settings
[success] Total time: 0 s, completed 15 ao¹t 2020 14:58:02
sbt:JSDepsRepro> update
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[success] Total time: 4 s, completed 15 ao¹t 2020 14:58:08
sbt:JSDepsRepro> projects
[info] In file:/C:/Users/sjrdo/Documents/Projets/JSDepsRepro/
[info]   * jsdepsrepro
sbt:JSDepsRepro> scalaJSNativeLibraries
[success] Total time: 0 s, completed 15 ao¹t 2020 14:58:49
sbt:JSDepsRepro> show scalaJSNativeLibraries
[info] Attributed(List())
[success] Total time: 0 s, completed 15 ao¹t 2020 14:58:52
sbt:JSDepsRepro> show compile:scalaJSNativeLibraries
[info] Attributed(List())
[success] Total time: 0 s, completed 15 ao¹t 2020 14:58:58
sbt:JSDepsRepro> packageJSDependencies
[error] stack trace is suppressed; run last Compile / resolvedJSDependencies for the full output
[error] (Compile / resolvedJSDependencies) org.scalajs.jsdependencies.core.JSLibResolveException: Some references to JS libraries could not be resolved:
[error] - Missing JS library: three.min.js
[error]   originating from: threejs-facade:compile
[error] - Missing JS library: three.js
[error]   originating from: threejs-facade:compile
[error] Total time: 0 s, completed 15 ao¹t 2020 14:59:36
sbt:JSDepsRepro> show fullClasspath
[info] * Attributed(C:\Users\sjrdo\Documents\Projets\JSDepsRepro\target\scala-2.12\classes)
[info] * Attributed(C:\Users\sjrdo\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.12.12\scala-library-2.12.12.jar)
[info] * Attributed(C:\Users\sjrdo\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-js\scalajs-library_2.12\1.1.1\scalajs-library_2.12-1.1.1.jar)
[info] * Attributed(C:\Users\sjrdo\AppData\Local\Coursier\cache\v1\https\maven.pkg.github.com\OpenGrabeso\packages\com\github\opengrabeso\threejs-facade_sjs1_2.12\0.0.114-0.0.4\threejs-facade_sjs1_2.12-0.0.114-0.0.4.jar)
[info] * Attributed(C:\Users\sjrdo\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-js\scalajs-dom_sjs1_2.12\1.0.0\scalajs-dom_sjs1_2.12-1.0.0.jar)
[success] Total time: 0 s, completed 15 ao¹t 2020 14:59:45
```

**Comment by OndrejSpanel** [comment]
Perhaps the issue is somehow platform or machine specific then, as I can reproduce it with the project anytime. The task for reproduction (I forgot to mention this) is `fastOptJS`.

It is quite possible Missing JS library  three.min.js in the jar is the real cause, but this is not the error I get when I use fastOptJS. When I try packageJSDependencies on my system I also get the error "Unable to determine if root directory exists", not the "Some references to JS libraries could not be resolved" you get.

**Comment by sjrd** [comment]
`fastOptJS` gives the same error as above for me:
```
sbt:JSDepsRepro> fastOptJS
[warn] undefined keys `githubOwner` and `githubRepository`
[warn] retaining pre-existing publication settings
[error] stack trace is suppressed; run last Compile / resolvedJSDependencies for the full output
[error] (Compile / resolvedJSDependencies) org.scalajs.jsdependencies.core.JSLibResolveException: Some references to JS libraries could not be resolved:
[error] - Missing JS library: three.min.js
[error]   originating from: threejs-facade:compile
[error] - Missing JS library: three.js
[error]   originating from: threejs-facade:compile
[error] Total time: 0 s, completed 15 ao¹t 2020 15:08:30
```

**Comment by OndrejSpanel** [comment]
Strange. All I get is the confusing error I have mentioned.

I have added the three.js and three.js.min as a ProvidedJS dependency into the project (I hope I got it right). Will this change anything on your end? I still get the same error with it as I got without.

**Comment by OndrejSpanel** [comment]
I can debug the sbt in necessary, but I admit I find the `createDirectories` confusing, I do not know what to look for.

**Comment by sjrd** [comment]
Perhaps this related to the fact that it's in the `D:` drive?

What you could try is to locally build a version sbt-dependencies where you replace this line:
https://github.com/scala-js/jsdependencies/blob/9e24fb77e11ed57592093b19c4c2469006d218f7/jsdependencies-sbt-plugin/src/main/scala/org/scalajs/jsdependencies/sbtplugin/JSDependenciesPlugin.scala#L157
with
```diff
-          val path = memFS.getPath(s"$jarPath/$relName")
+          val path = memFS.getPath(s"jarcontent/$relName")
```
If that fixes your problem, feel free to submit a PR.

**Comment by OndrejSpanel** [comment]
> What you could try is to locally build a version sbt-dependencies 

I will try. I never used a locally build plugin yet, but I hope I will be able to do it.

**Comment by OndrejSpanel** [comment]
I confirm the change you have suggested fixes the issue and I get the same behaviour as you do now: a sensible error without three.min.js and no error with it. I will prepare a PR.
